package bunshin

import "testing"

func TestPublicAPIContract(t *testing.T) {
	constructors := []any{
		DialPublication,
		DialExclusivePublication,
		ListenSubscription,
		StartMediaDriver,
		OpenDriverIPC,
		OpenDriverSubscriptionImage,
		OpenIPCRing,
		OpenArchive,
		StartArchiveControlServer,
		ListenArchiveControlProtocol,
		ReplicateArchive,
		StartClusterNode,
		StartClusterBackup,
		NewInMemoryClusterLog,
		NewInMemoryClusterSnapshotStore,
		NewArchiveClusterLog,
		NewArchiveClusterSnapshotStore,
		ListenClusterMemberTransport,
		DialClusterMember,
		NewClusterMembershipRuntime,
		NewDefaultBackoffIdleStrategy,
		NewBackoffIdleStrategy,
		NewMinMulticastFlowControl,
		NewPreferredMulticastFlowControl,
		NewAIMDUDPCongestionControl,
		ParseChannelURI,
	}
	configs := []any{
		PublicationConfig{},
		SubscriptionConfig{},
		DriverConfig{},
		DriverConnectionConfig{},
		DriverIPCConfig{},
		DriverSubscriptionImageConfig{},
		IPCRingConfig{},
		ArchiveConfig{},
		ArchiveReplayConfig{},
		ArchiveReplayMergeConfig{},
		ArchiveReplicationConfig{},
		ArchiveControlConfig{},
		ArchiveControlProtocolConfig{},
		ClusterConfig{},
		ClusterClientConfig{},
		ClusterLearnerConfig{},
		ClusterReplicationConfig{},
		ClusterElectionConfig{},
		ClusterQuorumConfig{},
		ClusterBackupConfig{},
		ClusterMemberTransportConfig{},
		ClusterMemberClientConfig{},
		ClusterMembershipRuntimeConfig{},
		ClusterMembershipRuntimeHooks{},
	}
	constants := []any{
		DriverThreadingShared,
		DriverThreadingDedicated,
		ArchiveControlProtocolVersion,
		ClusterMemberProtocolVersion,
	}
	errors := []error{
		ErrClosed,
		ErrInvalidConfig,
		ErrBackPressure,
		ErrInvalidChannelURI,
		ErrControlledPollAbort,
		ErrPublicationClaimClosed,
		ErrPublicationClaimAborted,
		ErrDriverClosed,
		ErrDriverClientClosed,
		ErrDriverResourceNotFound,
		ErrDriverExternalUnsupported,
		ErrDriverDirectoryActive,
		ErrDriverDirectoryUnavailable,
		ErrDriverProcessUnavailable,
		ErrDriverIPCClosed,
		ErrDriverIPCProtocol,
		ErrIPCRingClosed,
		ErrIPCRingFull,
		ErrIPCRingEmpty,
		ErrIPCRingMessageTooLarge,
		ErrIPCRingCorrupt,
		ErrArchiveClosed,
		ErrArchiveCorrupt,
		ErrArchivePosition,
		ErrArchiveRecordingActive,
		ErrArchiveRecordingNotActive,
		ErrArchiveControlClosed,
		ErrArchiveReplayMergeBufferFull,
		ErrArchiveReplayMergeClosed,
		ErrArchiveReplicationActiveRecording,
		ErrClusterClosed,
		ErrClusterSuspended,
		ErrClusterNotLeader,
		ErrClusterServiceUnavailable,
		ErrClusterLogClosed,
		ErrClusterLogPosition,
		ErrClusterLogEntryType,
		ErrClusterLearnerUnavailable,
		ErrClusterReplicationUnavailable,
		ErrClusterElectionUnavailable,
		ErrClusterQuorumUnavailable,
		ErrClusterTimerNotFound,
		ErrClusterSnapshotClosed,
		ErrClusterSnapshotStoreUnavailable,
		ErrClusterSnapshotUnsupported,
		ErrClusterBackupClosed,
		ErrClusterBackupUnsupported,
	}
	if len(constructors) == 0 || len(configs) == 0 || len(constants) == 0 || len(errors) == 0 {
		t.Fatal("public API contract is empty")
	}
}
